# Molecule managed

---
all:
  hosts:
    logrotate_debian_jessie: &id001
      ansible_connection: docker
    logrotate_debian_stretch: &id002
      ansible_connection: docker
    logrotate_debian_wheezy: &id003
      ansible_connection: docker
    logrotate_ubuntu_trusty: &id004
      ansible_connection: docker
    logrotate_ubuntu_xenial: &id005
      ansible_connection: docker
ungrouped:
  hosts:
    logrotate_debian_jessie: *id001
    logrotate_debian_stretch: *id002
    logrotate_debian_wheezy: *id003
    logrotate_ubuntu_trusty: *id004
    logrotate_ubuntu_xenial: *id005
  vars: {}
