---
- name: Install dependencies
  become: True
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - git
    - python-pip
    - python3-pip

- name: Install package
  become: True
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ program.packages }}"
  when: program.packages is defined
  tags:
    - install

- name: Install pip packages
  pip:
    name: "{{ item }}"
    executable: pip
    extra_args: --user
  with_items: "{{ program.pip_packages }}"
  when: program.pip_packages is defined
  tags:
    - install

- name: Install pip3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
  with_items: "{{ program.pip3_packages }}"
  when: program.pip3_packages is defined
  tags:
    - install
