---

- name: Install dependencies
  become: True
  apt:
    name:
      - git
      - python-pip
      - python3-pip
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install package
  become: True
  apt:
    name: "{{ install.packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: not install.packages == None

- name: Install pip packages
  pip:
    name: "{{ install.pip_packages }}"
    executable: pip
    extra_args: --user
  when: not install.pip_packages == None

- name: Install pip3 packages
  pip:
    name: "{{ install.pip3_packages }}"
    executable: pip3
    extra_args: --user
  when: not install.pip3_packages == None
