---
- name: Install package in Debian/Ubuntu/CentOS
  become: True
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ program.packages }}"
  when: program.packages is defined
  tags:
    - install

- name: Install pip packages
  pip:
    name: "{{ item }}"
    executable: pip
    extra_args: --user
  with_items: "{{ program.pip_packages }}"
  when: program.pip_packages is defined
  tags:
    - install

- name: Install pip3 packages
  pip:
    name: "{{ item }}"
    executable: pip3
    extra_args: --user
  with_items: "{{ program.pip3_packages }}"
  when: program.pip3_packages is defined
  tags:
    - install
