---
# tasks file for generic_program_install
- name: Install the program
  include_tasks: install.yml
  tags:
    - install

- name: Configure the program
  include_tasks: config.yml
  tags:
    - config
