---
# tasks file for generic_program_install

- name: Install the program
  include_tasks: install.yml

- name: Configure the program
  when: not config.packages == None
  include_tasks: config.yml
  loop: "{{ config.packages | default([]) }}"
  loop_control:
    loop_var: program_name
