---
# tasks file for generic_program_install
- name: Test not config
  debug:
    var: config
  when: not config.packages == None

- name: Test config
  debug:
    var: config
  when: config.packages == None

- name: Else
  debug:
    var: config

- fail:
- name: Install the program
  include_tasks: install.yml

- name: Configure the program
  include_tasks: config.yml
  loop: "{{ config.packages }}"
  loop_control:
    loop_var: program_name
  when: not config.packages == None
