---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: generic_install_debian_stretch
    image: debian:stretch
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  options:
    e: force_docker=yes
scenario:
  name: no_config
verifier:
  name: testinfra
  lint:
    name: flake8
